parameters:

    #
    # Templating
    #
    elcodi_plugin.javascript_renderer.class: Elcodi\Plugin\TwitterBundle\Templating\JavascriptRenderer
    elcodi_plugin.share_tweet_renderer.class: Elcodi\Plugin\TwitterBundle\Templating\ShareTweetRenderer
    elcodi_plugin.follow_renderer.class: Elcodi\Plugin\TwitterBundle\Templating\FollowRenderer
