plugin:
    type: plugin
    name: Twitter
    description: |
        Twitter social plugin.
    fa_icon: twitter
    fields:
        twitter_account:
            type: text
            label: elcodi_plugin.twitter.facebook_account
